import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Timbuktu - Sabedoria Ancestral</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Timbuktu</h1>

        <q className={styles.description}>
          O sal vem do norte, o ouro vem do sul, mas as palavras de Deus e os
          tesouros da sabedoria vêm de Timbuktu
        </q>
      </main>
    </div>
  );
}
